baseurl = "http://randomjohn.netlify.com"
languageCode = "en-us"
title = "Upstate Data Analysis"
theme = "hpstr-hugo-theme"
pluralizelisttitles = false
PygmentsCodeFences = true
Paginate = 5
disqusShortname = "randomjohn"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
googleAnalytics = "88844885"
twitter = "@randomjohn"
copyright = "(c) RJS Data Science LLC"


[permalinks]
    post = "/:year/:month/:day/:slug/"

[Data]
  [Data.sections]
    Title = "foo"

[params]
	subtitle = "Showcasing data analysis in R using public data about Greenville/Spartanburg, SC by RJS Data Science"
	[params.author]
		name = "John Johnson"
		avatar = "/images/avatar.jpg"
		bio = "Statistician from Upstate South Carolina"
		github = "randomjohn"
	[params.image]
	  feature = "/images/abstract-1.jpg"
	  credit = "dargadgetz"
	  creditlink = "http://www.dargadgetz.com/ios-7-abstract-wallpaper-pack-for-iphone-5-and-ipod-touch-retina/"
